# Generated by Django 4.2 on 2023-04-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
    ]
